version: "3"

services:
  
  frontend:
    image: jexniemi/frontend-example-docker
    build: ./frontend-example-docker
    container_name: frontend-example-docker
    ports: 
      - 5000:5000
    environment:
      - API_URL=http://localhost:8000

  backend:
    image: jexniemi/backend-example-docker
    build: ./backend-example-docker
    container_name: backend-example-docker
    ports: 
      - 8000:8000
    environment:
      - FRONT_URL=http://localhost:5000
